Add RFL template exporter
angryzor/sonic-frontiers-devtools pull request #29
Opened 2024-08-28 09:46 UTC by Ashrindy

2024-08-28 10:43 UTC, angryzor requested changes
Looks good, I pointed out some small changes, but if those are fixed it can be merged.

2024-08-28 10:43 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
>  	RflClassDef GenerateRflClass(Template& templateDef, const std::string& curNamespace, const hh::fnd::RflClass* rflClass) {
You're doing the copies again, and writing into the structs twice. Can you change the result type here to the `std::string` version please?

2024-08-28 10:43 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.h
> +	enum TemplateType {
Please use scoped enums.

2024-08-28 10:43 UTC, angryzor commented on src/ui/operation-modes/OperationMode.h
> -			if (behaviors[i]->behavior->GetId() == T::id) {
Huh?

2024-08-28 10:43 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +	class Flags {
Prefer struct for a newtype like this.

2024-08-28 10:43 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +			templateDef.structs[namespacedName] = GenerateRflClass(templateDef, "", member->GetStructClass());
Since the structs are no longer namespaced we can probably remove the `curNamespace` parameter on `GenerateRflClass`?

2024-08-28 10:46 UTC, Ashrindy commented on src/ui/operation-modes/OperationMode.h
> -			if (behaviors[i]->behavior->GetId() == T::id) {
I changed that because it was refusing to build, pushed it by accident mb

2024-08-28 11:19 UTC, Ashrindy commented on src/reflection/HSONTemplateGeneration.cpp
>  	RflClassDef GenerateRflClass(Template& templateDef, const std::string& curNamespace, const hh::fnd::RflClass* rflClass) {
for some reason, i still don't know why, but when i change it so the function outputs std::string, it exports incorrectly and all the structs have no fields or parents

2024-08-28 11:20 UTC, Ashrindy commented on src/reflection/HSONTemplateGeneration.h
> +	enum TemplateType {
done

2024-08-28 11:24 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
>  	RflClassDef GenerateRflClass(Template& templateDef, const std::string& curNamespace, const hh::fnd::RflClass* rflClass) {
It's because you're not assigning by reference here: https://github.com/angryzor/sonic-frontiers-devtools/pull/29/files/03bc1540a90ee2c5fbe8dc69dcc4fbeef11fee06#diff-90e5c24d1c90494b59211ea068026819b7bff1be83f129eb307d263a4b9b28b4R474

2024-10-08 19:34 UTC, angryzor requested changes
Sorry I'm so demanding lol

2024-10-08 19:34 UTC, angryzor commented on CMakeLists.txt
> +foreach(DEVTOOLS_TARGET_SDK rangers)
Please undo this change for obvious reasons 😅

2024-10-08 19:34 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +
Unnecessary newlines, wouldn't block just for this but since you have to fix the cmakelists.txt anyway.

2024-10-08 19:34 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +		std::optional<std::string> category{};
Please make a new TagDef instead. It is more strongly typed.

2024-10-08 19:34 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +	void GenerateTemplate(const std::string& filename, TemplateType type) {
Honestly, I know I suggested this myself, but we don't really need this switch or the TemplateType struct. Can you just make it 2 different functions?

2024-10-08 19:34 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +	void GenerateTemplate(const std::string& filename, TemplateType type) {
Note: I'm ok with you extracting the collections, thats useful. You can just make them helper functions with the same name (GenerateHSONTemplate...) but different signature.

2024-10-08 19:34 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +			}
I'm not a fan of the code duplication here. Can you extract the logic that generates the value for the `flags` property into a function that returns an std::nullopt please?

2024-10-08 19:34 UTC, angryzor commented on src/reflection/HSONTemplateGeneration.cpp
> +	RangeMemberDefT<T> GenerateRangeMemberT(const hh::fnd::RflClassMember* member, const char* typeName, const char* rangeAttrName, bool isflag = false) {
I don't like the addition of this isflag parameter because it continues my own antipattern that I started with the typeName parameter. Passing around duplicate information like this is kinda dirty. However, leave it as is, I'll check if both problems can be refactored afterwards, because it would need some changes in the code structure.

2024-10-08 19:34 UTC, angryzor commented on src/reflection/ReflectiveOperations.h
> +					return 0;
1. Please move this to another PR.
2. This code is broken. Missing UI display information would cause any operation on the RFL to not visit the flags at all. Instead please make enumEntries `nullptr` when this happens, and handle the edge case in the editor algorithm.

2024-10-08 19:38 UTC, Ashrindy commented on src/reflection/ReflectiveOperations.h
> +					return 0;
1. np
2. with some small tests, it's not crashing at all, i thought it'd crash but it doesn't seem like it. but i'll change it to nullptr anyway since it makes more sense

2024-10-08 20:28 UTC, angryzor approved these changes
LGTM. Thank you for this significant contribution!

2024-10-08 20:31 UTC, merged